### Final Project

Problem Statement - Predicting House price
 
> On Real world dataset

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRas9StvcoOlsgsa0iDJfXu8QrNrncUSFt75QHeMqT1Jw&s=10">

### California House Price Predection Project

Objective

> The objective of this project is to build a multiple linear regression model that predicts the median house value in California districts based on various features like:
* median income, 
* housing median age,
* and average room counts.

### Machine Learning Pipeline (Process)

* Data Collection and Import
* Exploratory Data Analysis & Data Cleaning (Handling Nulls and Duplicates)
* Feature Selection & Data Splitting
* Feature Scaling (Standardization)
* Model Building & Training
* Model Evaluation

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , r2_score

#### Step 1: Data Collection and Import
#### Load the dataset from a URL or local file path

In [3]:

data_url = "https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv"
df = pd.read_csv(data_url)

In [4]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [6]:
df.shape

(20640, 10)

In the feature called "Total_bedroom" with the meadin of the column

In [7]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [9]:
median_bedrooms = df["total_bedrooms"].median()
median_bedrooms

np.float64(435.0)

In [10]:
df["total_bedrooms"].isnull().sum()

np.int64(207)

### Enhancing the Model: One-Hot Encoding and Feature Engineering

In [11]:
df.fillna(median_bedrooms,inplace=True)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [12]:
df["total_bedrooms"].isnull().sum()

np.int64(0)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.6 MB

In [14]:
# Apply one-hot encoding to 'ocean_proximity'
df_encoded = pd.get_dummies(df, columns=['ocean_proximity'])

df_encoded.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False

### Feature Engineering.. 

> Creating new features (based on other features (columns,inputs,vectors) )

In [15]:
# Create new features
df_encoded['rooms_per_household'] = df_encoded['total_rooms'] / df_encoded['households']
df_encoded['bedrooms_per_room'] = df_encoded['total_bedrooms'] / df_encoded['total_rooms']
df_encoded['population_per_household'] = df_encoded['population'] / df_encoded['households']

df_encoded.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN,rooms_per_household,bedrooms_per_room,population_per_household
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False,6.984127,0.146591,2.555556
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False,6.238137,0.155797,2.109842
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False,8.288136,0.129516,2.802260
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False,5.817352,0.184458,2.547945
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False,6.281853,0.172096,2.181467

### Vertical split (to seprate input & output)

In [16]:
x=df_encoded.drop(columns="median_house_value")
#input

In [17]:
x.columns
# there is no median_house_value column now

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity_<1H OCEAN', 'ocean_proximity_INLAND',
       'ocean_proximity_ISLAND', 'ocean_proximity_NEAR BAY',
       'ocean_proximity_NEAR OCEAN', 'rooms_per_household',
       'bedrooms_per_room', 'population_per_household'],
      dtype='str')

In [18]:
y=df_encoded['median_house_value']
#storing the input data as output data

In [19]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

##  Horizontal Split (Train, Test)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# Split the data into training (80%) and testing (20%) sets
x_train_new, x_test_new, y_train_new, y_test_new = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
x_train_new

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN,rooms_per_household,bedrooms_per_room,population_per_household
14196,-117.03,32.71,33.0,3126.0,627.0,2300.0,623.0,3.2596,False,False,False,False,True,5.017657,0.200576,3.691814
8267,-118.16,33.77,49.0,3382.0,787.0,1314.0,756.0,3.8125,False,False,False,False,True,4.473545,0.232703,1.738095
17445,-120.48,34.66,4.0,1897.0,331.0,915.0,336.0,4.1563,False,False,False,False,True,5.645833,0.174486,2.723214
14265,-117.11,32.69,36.0,1421.0,367.0,1418.0,355.0,1.9425,False,False,False,False,True,4.002817,0.258269,3.994366
2271,-119.80,36.78,43.0,2382.0,431.0,874.0,380.0,3.5542,False,True,False,False,False,6.268421,0.180940,2.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,-117.96,33.78,35.0,1330.0,201.0,658.0,217.0,6.3700,True,False,False,False,False,6.129032,0.151128,3.032258
11964,-117.43,34.02,33.0,3084.0,570.0,1753.0,449.0,3.0500,False,True,False,False,False,6.868597,0.184825,3.904232
5390,-118.38,34.03,36.0,2101.0,569.0,1756.0,527.0,2.9344,True,False,False,False,False,3.986717,0.270823,3.332068
860,-121.96,37.58,15.0,3575.0,597.0,1777.0,559.0,5.7192,True,False,False,False,False,6.395349,0.166993,3.178891
15795,-122.42,37.77,52.0,4226.0,1315.0,2619.0,1242.0,2.5755,False,False,False,True,False,3.402576,0.311169,2.108696

standardisation

In [23]:
from sklearn.preprocessing import StandardScaler
# Initalize the StandardScaler
scaler_new = StandardScaler()

# Fit & transform the training features
x_train_scaled_new = scaler_new.fit_transform(x_train_new) # mean & standard deveation

# Transform the testing features using the training set scaler
x_test_scaled_new = scaler_new.transform(x_test_new) #mean & standard deveation

In [24]:
## use the regression model
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

In [25]:
pd.DataFrame(x_test_scaled_new,y_test_new).info()

<class 'pandas.DataFrame'>
Index: 4128 entries, 47700.0 to 151500.0
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4128 non-null   float64
 1   1       4128 non-null   float64
 2   2       4128 non-null   float64
 3   3       4128 non-null   float64
 4   4       4128 non-null   float64
 5   5       4128 non-null   float64
 6   6       4128 non-null   float64
 7   7       4128 non-null   float64
 8   8       4128 non-null   float64
 9   9       4128 non-null   float64
 10  10      4128 non-null   float64
 11  11      4128 non-null   float64
 12  12      4128 non-null   float64
 13  13      4128 non-null   float64
 14  14      4128 non-null   float64
 15  15      4128 non-null   float64
dtypes: float64(16)
memory usage: 548.2 KB

In [26]:
lr.fit(x_train_scaled_new,y_train_new)

LinearRegression()

In [27]:
y_predict = lr.predict(x_test_scaled_new)

In [28]:
## model evaluation 
from sklearn.metrics import r2_score,root_mean_squared_error
print("RMSE:",root_mean_squared_error(y_test_new,y_predict))
print("R2_Score:",r2_score(y_test_new,y_predict))

RMSE: 72668.53837868226
R2_Score: 0.5970176824350761

------------------------------------------------------------------------------------------------------------------------------------

## RandomForestregression is more accurate

> Ensebmble lesarning algorithim 

> Models used = Decision Tree

> For classification -Majority 

> For regression - Average

<img src="https://www.slideteam.net/media/catalog/product/cache/1280x720/f/r/framework_of_random_forest_regression_algorithm_ppt_sample_slide01.jpg">

In [29]:
## Change the model to RandomForestRegression
from sklearn.ensemble import RandomForestRegressor

rf= RandomForestRegressor(n_estimators=100,random_state=42)
rf.fit(x_train_scaled_new,y_train_new)
rfpredict=rf.predict(x_test_scaled_new)
print("RMSE:",root_mean_squared_error(y_test_new,y_predict))
print("R2_Score:",r2_score(y_test_new,y_predict))

RMSE: 72668.53837868226
R2_Score: 0.5970176824350761

>> Random Forest  Regressor has higher performance compare to Linear Regression

In [30]:
import pickle
pickle.dump(rf,open("rfmodel.pkl","wb"))